import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider";
import { Navbar } from "./components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { CartDrawer } from "./components/CartDrawer";

export const metadata: Metadata = {
  title: "Gharo Ghari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <header>
            <Navbar />
          </header>
          <main>{children}</main>
          <Toaster position="top-center" />
          <CartDrawer />
        </AuthProvider>
      </body>
    </html>
  );
}
